# implicitly
disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
#- force_try

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- R.generated.swift

line_length:
    warning: 400
    error: 500

opt_in_rules: # some rules are only opt-in
- force_unwrapping

large_tuple: 3
function_parameter_count: 10
